service: mozio-geofence
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /mozio-geofence/api/apikey.*
  script: api.apikey.endpoint
  secure: always

- url: /mozio-geofence/api/territory.*
  script: api.territory.endpoint
  secure: always

- url: /mozio-geofence/api/provider.*
  script: api.provider.endpoint
  secure: always

- url: /mozio-geofence/api/territory.*
  script: api.territory.endpoint
  secure: always

- url: /mozio-geofence.*
  static_files: apiexplorer.html
  upload: apiexplorer\.html
  secure: always



