service: mozio-geofence
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /api/provider.*
  script: api.provider.endpoint
  secure: always

- url: /api/territory.*
  script: api.territory.endpoint
  secure: always

- url: /.*
  static_files: apiexplorer.html
  upload: apiexplorer\.html
  secure: always



